// Mocks generated by Mockito 5.4.4 from annotations
// in life_tracker/test/features/health/presentation/providers/medication_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:life_tracker/core/errors/failures.dart' as _i6;
import 'package:life_tracker/features/health/domain/entities/medication.dart'
    as _i7;
import 'package:life_tracker/features/health/domain/entities/medication_intake.dart'
    as _i15;
import 'package:life_tracker/features/health/domain/repositories/medication_repository.dart'
    as _i2;
import 'package:life_tracker/features/health/domain/usecases/add_medication.dart'
    as _i4;
import 'package:life_tracker/features/health/domain/usecases/calculate_adherence.dart'
    as _i13;
import 'package:life_tracker/features/health/domain/usecases/delete_medication.dart'
    as _i10;
import 'package:life_tracker/features/health/domain/usecases/get_medication_intakes.dart'
    as _i14;
import 'package:life_tracker/features/health/domain/usecases/get_medications.dart'
    as _i8;
import 'package:life_tracker/features/health/domain/usecases/mark_medication_taken.dart'
    as _i11;
import 'package:life_tracker/features/health/domain/usecases/snooze_medication.dart'
    as _i12;
import 'package:life_tracker/features/health/domain/usecases/update_medication.dart'
    as _i9;
import 'package:life_tracker/features/health/services/medication_notification_service.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMedicationRepository_0 extends _i1.SmartFake
    implements _i2.MedicationRepository {
  _FakeMedicationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddMedication extends _i1.Mock implements _i4.AddMedication {
  MockAddMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, int>> call(_i7.Medication? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, int>>.value(
            _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, int>>);
}

/// A class which mocks [GetMedications].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMedications extends _i1.Mock implements _i8.GetMedications {
  MockGetMedications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Medication>>> call(
          _i8.GetMedicationsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Medication>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Medication>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Medication>>>);
}

/// A class which mocks [UpdateMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateMedication extends _i1.Mock implements _i9.UpdateMedication {
  MockUpdateMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i7.Medication? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [DeleteMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMedication extends _i1.Mock implements _i10.DeleteMedication {
  MockDeleteMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(int? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [MarkMedicationTaken].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkMedicationTaken extends _i1.Mock
    implements _i11.MarkMedicationTaken {
  MockMarkMedicationTaken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
          _i11.MarkMedicationTakenParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [SnoozeMedication].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnoozeMedication extends _i1.Mock implements _i12.SnoozeMedication {
  MockSnoozeMedication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
          _i12.SnoozeMedicationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [CalculateAdherence].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateAdherence extends _i1.Mock
    implements _i13.CalculateAdherence {
  MockCalculateAdherence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, double>> call(int? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, double>>.value(
            _FakeEither_1<_i6.Failure, double>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, double>>);
}

/// A class which mocks [GetMedicationIntakes].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMedicationIntakes extends _i1.Mock
    implements _i14.GetMedicationIntakes {
  MockGetMedicationIntakes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MedicationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMedicationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MedicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i15.MedicationIntake>>> call(
          _i14.GetMedicationIntakesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i15.MedicationIntake>>>.value(
            _FakeEither_1<_i6.Failure, List<_i15.MedicationIntake>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i15.MedicationIntake>>>);
}

/// A class which mocks [MedicationNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationNotificationService extends _i1.Mock
    implements _i16.MedicationNotificationService {
  MockMedicationNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> scheduleMedicationNotifications(
          _i7.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMedicationNotifications,
          [medication],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelMedicationNotifications(int? medicationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelMedicationNotifications,
          [medicationId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> rescheduleAllMedicationNotifications(
          List<_i7.Medication>? medications) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescheduleAllMedicationNotifications,
          [medications],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
